# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='plantillatarjeta',
            options={'verbose_name_plural': 'Plantillas de tarjetas'},
        ),
        migrations.AlterModelOptions(
            name='profesion',
            options={'verbose_name_plural': 'Profesiones'},
        ),
        migrations.AlterModelOptions(
            name='rubro',
            options={'verbose_name_plural': 'Rubros'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'verbose_name_plural': 'Tarjetas'},
        ),
        migrations.AlterModelOptions(
            name='telefonousuario',
            options={'verbose_name_plural': 'Telefonos Usuarios'},
        ),
        migrations.AlterField(
            model_name='profesion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
