# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tarjeta_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
    ]
