# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 04:16
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170311_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='id',
        ),
        migrations.AlterField(
            model_name='pais',
            name='cca2',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='logo',
            field=models.ImageField(blank=True, upload_to=core.models.upload_path),
        ),
    ]
