# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170727_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=30)),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(max_length=300)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
